# Generated by Django 4.1.7 on 2023-08-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='visitors.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology')], max_length=50),
        ),
    ]
